// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var BlogComponent$ReactHooksTemplate = require("./BlogComponent.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(BlogComponent$ReactHooksTemplate.make, { }), "blog-component");

/*  Not a pure module */
